name: Checks

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Screenly/edge-apps-actions/checks@f4ccd2bd50db5fb0a5147d287ac03cafe552d29b
